COMPONENT_DEPENDS = IOControl

#
ifeq ($(SMING_ARCH),Host)
COMPONENT_RELINK_VARS += USE_LOCAL_FILESYSTEM
USE_LOCAL_FILESYSTEM ?= 0
ifeq ($(USE_LOCAL_FILESYSTEM),1)
COMPONENT_CPPFLAGS += -DUSE_LOCAL_FILESYSTEM
endif
endif
