COMPONENT_DEPENDS = IOControl
COMPONENT_SRCDIRS := src
COMPONENT_INCDIRS := src/include
COMPONENT_DOXYGEN_INPUT := src/include

#
ifeq ($(SMING_ARCH),Host)
COMPONENT_RELINK_VARS += USE_LOCAL_FILESYSTEM
USE_LOCAL_FILESYSTEM ?= 0
ifeq ($(USE_LOCAL_FILESYSTEM),1)
COMPONENT_CPPFLAGS += -DUSE_LOCAL_FILESYSTEM
endif
endif
